package com.drawingly;


public class DefaultWords {
    
    public static final String DEFAULT_WORDS =
        
        "angle\n" +
        "ant\n" +
        "apple\n" +
        "arch\n" +
        "arm\n" +
        "army\n" +
        "baby\n" +
        "bag\n" +
        "ball\n" +
        "band\n" +
        "basin\n" +
        "basket\n" +
        "bath\n" +
        "bed\n" +
        "bee\n" +
        "bell\n" +
        "berry\n" +
        "bird\n" +
        "blade\n" +
        "board\n" +
        "boat\n" +
        "bone\n" +
        "book\n" +
        "boot\n" +
        "bottle\n" +
        "box\n" +
        "boy\n" +
        "brain\n" +
        "brake\n" +
        "branch\n" +
        "brick\n" +
        "bridge\n" +
        "brush\n" +
        "bucket\n" +
        "bulb\n" +
        "button\n" +
        "cake\n" +
        "camera\n" +
        "card\n" +
        "cart\n" +
        "carriage\n" +
        "cat\n" +
        "chain\n" +
        "cheese\n" +
        "chest\n" +
        "chin\n" +
        "church\n" +
        "circle\n" +
        "clock\n" +
        "cloud\n" +
        "coat\n" +
        "collar\n" +
        "comb\n" +
        "cord\n" +
        "cow\n" +
        "cup\n" +
        "curtain\n" +
        "cushion\n" +
        "dog\n" +
        "door\n" +
        "drain\n" +
        "drawer\n" +
        "dress\n" +
        "drop\n" +
        "ear\n" +
        "egg\n" +
        "engine\n" +
        "eye\n" +
        "face\n" +
        "farm\n" +
        "feather\n" +
        "finger\n" +
        "fish\n" +
        "flag\n" +
        "floor\n" +
        "fly\n" +
        "foot\n" +
        "fork\n" +
        "fowl\n" +
        "frame\n" +
        "garden\n" +
        "girl\n" +
        "glove\n" +
        "goat\n" +
        "gun\n" +
        "hair\n" +
        "hammer\n" +
        "hand\n" +
        "hat\n" +
        "head\n" +
        "heart\n" +
        "hook\n" +
        "horn\n" +
        "horse\n" +
        "hospital\n" +
        "house\n" +
        "island\n" +
        "jewel\n" +
        "kettle\n" +
        "key\n" +
        "knee\n" +
        "knife\n" +
        "knot\n" +
        "leaf\n" +
        "leg\n" +
        "library\n" +
        "line\n" +
        "lip\n" +
        "lock\n" +
        "map\n" +
        "match\n" +
        "monkey\n" +
        "moon\n" +
        "mouth\n" +
        "muscle\n" +
        "nail\n" +
        "neck\n" +
        "needle\n" +
        "nerve\n" +
        "net\n" +
        "nose\n" +
        "nut\n" +
        "office\n" +
        "orange\n" +
        "oven\n" +
        "parcel\n" +
        "pen\n" +
        "pencil\n" +
        "picture\n" +
        "pig\n" +
        "pin\n" +
        "pipe\n" +
        "plane\n" +
        "plate\n" +
        "plow\n" +
        "pocket\n" +
        "pot\n" +
        "potato\n" +
        "prison\n" +
        "pump\n" +
        "rail\n" +
        "rat\n" +
        "receipt\n" +
        "ring\n" +
        "rod\n" +
        "roof\n" +
        "root\n" +
        "sail\n" +
        "school\n" +
        "scissors\n" +
        "screw\n" +
        "seed\n" +
        "sheep\n" +
        "shelf\n" +
        "ship\n" +
        "shirt\n" +
        "shoe\n" +
        "skin\n" +
        "skirt\n" +
        "snake\n" +
        "sock\n" +
        "spade\n" +
        "sponge\n" +
        "spoon\n" +
        "spring\n" +
        "square\n" +
        "stamp\n" +
        "star\n" +
        "station\n" +
        "stem\n" +
        "stick\n" +
        "stocking\n" +
        "stomach\n" +
        "store\n" +
        "street\n" +
        "sun\n" +
        "table\n" +
        "tail\n" +
        "thread\n" +
        "throat\n" +
        "thumb\n" +
        "ticket\n" +
        "toe\n" +
        "tongue\n" +
        "tooth\n" +
        "town\n" +
        "train\n" +
        "tray\n" +
        "tree\n" +
        "trousers\n" +
        "umbrella\n" +
        "wall\n" +
        "watch\n" +
        "wheel\n" +
        "whip\n" +
        "whistle\n" +
        "window\n" +
        "wing\n" +
        "wire\n" +
        "worm";

}
